### ISSUE TITLE
Words do not match if one ends with a special character and the other does not

### ISSUE THREAD

**Issue by gesundkrank** [picapica-org/jQuery.picadiff#5]
![screenshot from 2013-08-01 14 32 36](https://f.cloud.github.com/assets/493319/893516/e4cde8e8-faa6-11e2-82c2-2b404b79fcdb.png)

Last word in this example should match!

**Comment by potthast** [comment]
Dieses Problem besteht noch immer...
![errors](https://f.cloud.github.com/assets/1148967/1933804/13d8605a-7ee1-11e3-9d00-7f872bdb4953.png)

**Comment by gesundkrank** [comment]
Für eckige Klammern funktioniert es jetzt.
